import { Link } from 'react-router-dom'
import { LandingNav } from '@/components/landing/LandingNav'

export function TermsPage() {
  return (
    <div className="min-h-screen flex flex-col w-full bg-dark text-landing-white font-dm-sans">
      <LandingNav />
      <main className="flex-1 max-w-3xl mx-auto px-6 py-12">
        <Link to="/" className="text-sm text-white-dim hover:text-landing-white mb-6 inline-block">
          ← Back to home
        </Link>
        <h1 className="text-3xl font-bold text-landing-white mb-2">Terms of Service</h1>
        <p className="text-sm text-white-dim mb-2">End-User License Agreement</p>
        <p className="text-sm text-white-dim mb-10">Last updated: March 2026</p>

        <div className="prose prose-invert prose-sm max-w-none space-y-6 text-white-dim leading-relaxed">
          <section>
            <h2 className="text-lg font-semibold text-landing-white mt-8 mb-2">1. Acceptance</h2>
            <p>
              By signing up for or using Proj-X (“Service”), you agree to these Terms of Service and our Privacy Policy. If you are using the Service on behalf of an organization, you represent that you have authority to bind that organization to these terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-landing-white mt-8 mb-2">2. License and use</h2>
            <p>
              We grant you a limited, non-exclusive, non-transferable license to access and use the Service for your internal business purposes in accordance with your subscription plan. You may not resell, redistribute, or use the Service to build a competing product. You are responsible for maintaining the security of your account and for all activity under your account.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-landing-white mt-8 mb-2">3. Your content and data</h2>
            <p>
              You retain ownership of the data and content you upload or create in the Service. You grant us the rights necessary to operate, store, and display that content as part of the Service. You represent that you have the right to provide such content and that it does not violate any third-party rights or applicable law.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-landing-white mt-8 mb-2">4. Third-party integrations</h2>
            <p>
              The Service may allow you to connect third-party services (e.g. QuickBooks). Your use of those services is subject to their terms and policies. We are not responsible for the availability, accuracy, or conduct of third-party services.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-landing-white mt-8 mb-2">5. Disclaimers</h2>
            <p>
              The Service is provided “as is” and “as available.” We disclaim all warranties, express or implied, including merchantability and fitness for a particular purpose. We do not guarantee that the Service will be uninterrupted, error-free, or secure. Material takeoffs and estimates generated by the Service are for informational use; you are responsible for verifying accuracy before relying on them.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-landing-white mt-8 mb-2">6. Limitation of liability</h2>
            <p>
              To the maximum extent permitted by law, Proj-X and its affiliates shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or for loss of profits, data, or goodwill, arising from your use of the Service. Our total liability shall not exceed the amount you paid us in the twelve months preceding the claim.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-landing-white mt-8 mb-2">7. Termination</h2>
            <p>
              We may suspend or terminate your access to the Service for breach of these terms or for any other reason with notice where required. You may stop using the Service at any time. Upon termination, your right to use the Service ceases; we may retain or delete your data in accordance with our Privacy Policy and applicable law.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-landing-white mt-8 mb-2">8. Changes</h2>
            <p>
              We may update these terms from time to time. We will notify you of material changes by posting the updated terms and, where appropriate, by email or in-app notice. Continued use of the Service after changes constitutes acceptance of the revised terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-landing-white mt-8 mb-2">9. Contact</h2>
            <p>
              For questions about these Terms of Service, contact us at the email or address provided in the app or on our website.
            </p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-border-dark">
          <Link to="/privacy" className="text-accent hover:underline">Privacy Policy</Link>
          <span className="text-white-dim mx-2">·</span>
          <Link to="/" className="text-accent hover:underline">Home</Link>
        </div>
      </main>
    </div>
  )
}
